"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

import os
import sys
import environ


env = environ.Env()
# environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Celery

# CELERY_BROKER_URL = "redis://redis:6379"
# CELERY_RESULT_BACKEND = "redis://redis:6379"

# CELERY_BROKER_URL = env('REDIS_URL')
CELERY_BROKER_URL = os.environ.get('REDIS_URL')

# CELERY_RESULT_BACKEND = env('REDIS_URL')  # this is the option for redis performance, doesn't show in flower maybe
# CELERY_RESULT_BACKEND = 'django-db'  # this shows in django_celery_results
# CELERY_RESULT_BACKEND = env('REDIS_URL')

# CELERY_RESULT_BACKEND = env('POSTGRES_DATABASE')
CELERY_RESULT_BACKEND = 'django-db'  # for django celery results
# CELERY_CACHE_BACKEND = 'django-cache'  # for django celery results
CELERY_CACHE_BACKEND = 'default'  # for redis
CELERY_RESULT_EXTENDED = True

CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = "Europe/London"

